server:
  port: 8080

spring:
  application:
    name: easyeventbus-demo

# EasyEventBus配置
easyeventbus:
  enable: true
  identifier: demoEventBus
  asyncEnabled: false
  asyncThreadPoolSize: 10

logging:
  level:
    com.tobyang: DEBUG
    com.tobyang.easyeventbus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
